// Shared formatting for every hand-off target (GitHub issue, Jira ticket, or
// a plain copy) so the title/body shape is identical regardless of where it
// lands.

export interface HandoffSource {
  departmentName: string;
  useCase: string;
  outputFormat: string;
  technique: string;
  qualityScore: number | null;
  prompt: string;
}

export function handoffTitle(src: HandoffSource): string {
  return `${src.departmentName}: ${src.useCase}`;
}

export function handoffBody(src: HandoffSource): string {
  const meta = [
    `Output: ${src.outputFormat}`,
    `Technique: ${src.technique}`,
    src.qualityScore !== null ? `Quality score: ${src.qualityScore}/100` : null,
    "Generated by PromptForge.",
  ]
    .filter(Boolean)
    .join(" · ");
  return `${src.prompt}\n\n---\n${meta}`;
}
